[project]
name = "ra-distaso2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cupy-cuda12x>=14.1.1",
    "cutensor-cu12>=2.7.0",
    "duckdb>=1.5.4",
    "einops>=0.8.2",
    "great-tables>=0.24.0",
    "h5py>=3.16.0",
    "numpy>=2.5.1",
    "pandas-market-calendars>=5.4.0",
    "plotnine>=0.15.7",
    "polars>=1.42.1",
    "pyarrow>=24.0.0",
    "requests>=2.34.2",
    "tdqm>=0.0.1",
    "threadpoolctl>=3.6.0",
    "typing>=3.10.0.0",
]

[external]
dependencies = [
    "pkg:generic/latexmk>=4.0",
    "pkg:generic/quarto>=1.0.0",
    "pkg:generic/git>=2.0.0",
    "pkg:generic/uv>=0.9.0",
]

[dependency-groups]
dev = [
    "debugpy>=1.8.21",
    "pip>=26.1.2",
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.8",
]
